language: python
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    dist: xenial
    python: '3.7'
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
install:
- pip3 install -r requirements.txt
- pip3 install pyinstaller
script:
- |
  pyinstaller -c --onefile --hidden-import=celery --hidden-import=celery.fixups --hidden-import=celery.fixups.django
  spinveyor/spinveyor.py; 
  tar -czvf dist/spinveyor_$TRAVIS_OS_NAME.tar.gz dist/spinveyor

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  overwrite: true
  api_key:
    secure: CkBCkzy5lSdixFY1olaFCu8w1O02tBqjRgMmBUvKJCSDNRDiDxcb89TTaCw5vST+OaUrX+jqT0s1EiHAjDNNBguXQduDpSXaMm6E0eJC50sXPGheolI5bpV4gCxnLIKJq9rnHid+HZv7mDXsn17HWwWXSxGs7iYoYvbleSsz+otWfF2H6cA1HXsk7sJ3XiZb/T8YHZzjvgex9pmzq4V+fnmxPotK2cUbY+pwxiOBvoqNlJrxF7BhTf0Lpu+mwy84JkxmHBy+bb4iqCxXHEqjtPaYRBVHgT9osDwaULwJ6pVw4hjlrMKcyzIqDnqENDV4Ce57UN1ncS31twcr6pEUzX+2NzvBMhJLyPsZ/dTH40AJZUyR3/dnM4EqSKX09RiQeez2R8JTpLZgaC3CU3KmANEbu0bcjXN09/jneRIVPNvwd7QA3HI6lrC7C9vQAMv7WcPBEhGONgG5TKLCAZfgo//zurflngyLE1RKvLx3p7doPOOTCs2o3wm5l8ogvcNMaVUvFx7BSH4ZXj/I/qk9EAlc1fSrmc4nn5/7ze1xX3jeqdGpC/iQVCc32hVXbI/JejyVU3X0OQ0hJMhlvMfz7WPBalkAp1auPKfYDP96RnrJihSMkQuGzonwIFzZAaq4O/sdjl+Ta2/bQ43sd2nBQYq6UxoqmLeN3sRGUkzNCek=
  file_glob: on
  file: dist/spinveyor_*.tar.gz
  on:
    repo: spinveyor/spinveyor
