language: python
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    dist: xenial
    python: '3.7'
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
install:
- pip3 install -r requirements.txt
- pip3 install pyinstaller
script:
- |
  pyinstaller -c --onefile --hidden-import=celery --hidden-import=celery.fixups --hidden-import=celery.fixups.django spinveyor/spinveyor.py
  tar -czvf dist/spinveyor_$TRAVIS_OS_NAME.tar.gz dist/spinveyor
deploy:
  skip_cleanup: true
  draft: true
  overwrite: true
  provider: releases
  api_key:
    secure: kby9a+0J0r4HU8+y2RZXToz4DflO5JwBP/L10OYw5fVDCLS5DET8Qf7WyXIpWmkD9NG/NUcRaKxYZ4sbj3CIqfnCcSQc/Duo1k+FwgWzhp+LgmAh5asYQllzfyFzCso+lSMWHMikOTDubA9KlYvNhdrrkPGPTSH6cTxsTkQ7K7YRCZHYAvMvYr6j1lhk7gLjEjtHTdY9abkcNpwk7OR1lQ+ASJ19pgTByiZk6BvanuJWddrXtG6UEOYg0IXRG94rL6H7neZqdMKUUnnuRn472ySymhikjFu/SgeCoivarCR57Av+rh79XxbXeJfWqttFeBikoHs5+a3a2TQkl8KwdbLN2mzUmdaGTFzQ7iu0wWYVWLOeh7CoO+PVqkKWnAnBub9lWaIn4qeLB9RZ2iefUHa06gCzCa5PfwQzPL3xKUSyNbMANK+s6SdcsBjzWiGZtjXTi/ncEV8ojpIC66G+h5UzkJ/sqD0g7NQLgZr45ky9qkjRnYy/2MhlnDtJBRb/G3dTWYLiJutDyGFAW9dQz9igDHI6dCH55t3LRT10moHx7u+T3IUZoID4e/5A2s7QidWd7EWqwrKl8BVQWCQEQm/EzF0NrvBatMu10NuEW48xTLUBfZzYd224EFb3iHNZboQvb1Y2QsKYmXm6Oj4wf1CxO7VMucu0c28xDGRsJls=
  file: dist/spinveyor_*.tar.gz
  on:
    repo: spinveyor/spinveyor
