version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    volumes:
      - ${RABBITMQ_CONFIG_FILE}:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
    expose:
      - 15672/tcp
      - 15672/udp

  flower:
    image: mher/flower
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    command: "celery --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672 flower --port=5555 --broker-api=http://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:15672/api --url_prefix=/flower"
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - flower
