version: '3.4'
services:
  redis:
    image: redis

  flower:  
    image: mher/flower
    command: flower --port=5555 --broker=redis://redis:6379/0
    ports:  
      - 5555:5555
    depends_on:
      - redis