version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.7.8

  flower:  
    image: mher/flower
    command: flower --port=5555
    environment:
      - CELERY_BROKER_URL
      - FLOWER_PORT=5555
    ports:  
      - 5555:5555
 